version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    build: .
    container_name: openvpn
    environment:
     - DEBUG=1
    ports:
     - "1194:1194/udp"
    restart: always
    mem_limit: 128mb
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
     - ./openvpn-data/clients:/etc/openvpn/clients


networks:
  default:
    name: a1vpn
    external: true
